on:
  schedule:
    # https://crontab.guru/every-hour
    - cron: 0 * * * *
name: Update
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: git checkout schema-update || true
      - run: npm ci
      - run: npm run update
      - name: create pull request
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "🚧 🤖📯 GraphQL Schema changed"
          body: |
            I found new changes in GitHub's GraphQL Schema 👋🤖

            I can't tell if the changes are fixes, features or breaking, you'll have to figure that out on yourself and adapt the commit messages accordingly to trigger the right release, see [our commit message conventions](https://github.com/octokit/routes/blob/master/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).
          branch: "schema-update"
          author: "Octokit Bot <octokitbot@martynus.net>"
          path: "schema.graphql"
          commit-message: "WIP: schema.graphql changed - please review"
      - name: update schema.json
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "schema-update"
          author: "Octokit Bot <octokitbot@martynus.net>"
          path: "schema.json"
          commit-message: "build: schema.json updated"
